version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.418-jdk11
    privileged: true
    user: root
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_configuration:/var/jenkins_home

  agent:
    image: jenkins/ssh-agent:jdk11
    env_file:
        - .env
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}